#use_frameworks!

platform :ios, '8.0'

target 'JKDeafultView_Example' do
  pod 'JKDeafultView', :path => '../'

  target 'JKDeafultView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
